name: Health Check

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
  schedule:
    - cron: '*/5 11 * * *'

jobs:
  health_check_action:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Check the pokedex URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://mypokedex.fly.dev/
